name: Populate

on:
  workflow_dispatch:

jobs:
  get-unpopulated-ports:
    environment: build-cache
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Log into Azure
      contents: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: List artifacts that need to be populated
        shell: pwsh
        run: |
          ./Get-UncachedPorts.ps1 `
            -AccountName ${{ vars.STORAGE_ACCOUNT_NAME }} `
            -ContainerName vcpkg-assets | Set-Content artifacts-to-populate.txt

      - name: Upload artifacts-to-populate.txt
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-to-populate
          path: artifacts-to-populate.txt

  build-cache:
    environment: build-cache
    needs: get-unpopulated-ports

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            triplets: x64-linux
          - os: windows-2022
            triplets: x64-uwp
          - os: windows-2022
            triplets: x64-windows-static
          - os: windows-2022
            triplets: x64-windows
          - os: windows-2022
            triplets: x86-windows
          - os: macos-12
            triplets: x64-osx

    runs-on: ${{ matrix.os }}

    permissions:
      id-token: write # Log into Azure
      contents: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set core.longPaths
        if: runner.os == 'Windows'
        shell: pwsh
        run: git config --system core.longPaths true

      - name: Get storage key
        shell: pwsh
        run: |
          # Output is quoted, so ConvertFrom-Json to get the value without 
          # the quotes
          $key = az storage container generate-sas `
            --account-name ${{ vars.STORAGE_ACCOUNT_NAME }} `
            --auth-mode login `
            --as-user `
            --name vcpkg-assets `
            --permissions aclmrw `
            --expiry ((Get-Date -AsUTC).AddHours(6).ToString("yyyy-MM-dd'T'HH:mm'Z'")) `
            --output json | ConvertFrom-Json

          Write-Host "::add-mask::$key"
          "STORAGE_KEY=$key" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Download artifacts-to-populate.txt
        uses: actions/download-artifact@v3
        with:
          name: artifacts-to-populate

      - name: Populate artifacts
        shell: pwsh
        env:
          X_VCPKG_ASSET_SOURCES: x-azurl,https://${{ vars.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/vcpkg-assets,${{ env.STORAGE_KEY }},readwrite
        run: >-
          ./go.ps1 
          -OutFile result-${{ matrix.os }}-${{ matrix.triplet }}.json 
          -Triplets "${{ matrix.triplets }}"
          -Ports (Get-Content artifacts-to-populate.txt)
      
      - name: Upload result log
        uses: actions/upload-artifact@v3
        with:
          name: result-log
          path: result*.json
