name: Populate

on:
  workflow_dispatch:

jobs:
  build-cache:
    environment: build-cache
    runs-on: ubuntu-22.04

    permissions:
      id-token: write # Log into Azure

    steps:
      - uses: actions/checkout
      
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get storage key
        shell: pwsh
        run: |
          # Output is quoted, so ConvertFrom-Json to get the value without 
          # the quotes
          $key = az storage container generate-sas `
            --account-name ${{ env.STORAGE_ACCOUNT_NAME }} `
            --auth-mode login `
            --as-user `
            --name vcpkg-assets `
            --permissions aclmrw `
            --expiry ((Get-Date -AsUtc).AddHours(6).ToString('o')) `
            --output json | ConvertFrom-Json

          Write-Host "::add-mask::$key"
          "STORAGE_KEY=$key" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Populate artifacts
        shell: pwsh
        run: ./go.ps1 -OutFile result.json
      
      - name: Upload result log
        uses: actions/upload-artifact@v3
        with:
          name: result-log
          path: result.json
